DROP TABLE IF EXISTS clave_instituciones;
CREATE TABLE clave_instituciones(
id INTEGER,
nombre TEXT,
PRIMARY KEY(id));

INSERT INTO clave_instituciones VALUES(2001 ,'BANXICO');
INSERT INTO clave_instituciones VALUES(37006,'BANCOMEXT');
INSERT INTO clave_instituciones VALUES(37009,'BANOBRAS');
INSERT INTO clave_instituciones VALUES(37019,'BANJERCITO');
INSERT INTO clave_instituciones VALUES(37135,'NAFIN');
INSERT INTO clave_instituciones VALUES(37166,'BANSEFI');
INSERT INTO clave_instituciones VALUES(37168,'HIPOTECARIA FED');
INSERT INTO clave_instituciones VALUES(40002,'BANAMEX');
INSERT INTO clave_instituciones VALUES(40012,'BBVA BANCOMER');
INSERT INTO clave_instituciones VALUES(40014,'SANTANDER');
INSERT INTO clave_instituciones VALUES(40021,'HSBC');
INSERT INTO clave_instituciones VALUES(40030,'BAJIO');
INSERT INTO clave_instituciones VALUES(40036,'INBURSA');
INSERT INTO clave_instituciones VALUES(40042,'MIFEL');
INSERT INTO clave_instituciones VALUES(40044,'SCOTIABANK');
INSERT INTO clave_instituciones VALUES(40058,'BANREGIO');
INSERT INTO clave_instituciones VALUES(40059,'INVEX');
INSERT INTO clave_instituciones VALUES(40060,'BANSI');
INSERT INTO clave_instituciones VALUES(40062,'AFIRME');
INSERT INTO clave_instituciones VALUES(40072,'BANORTE');
INSERT INTO clave_instituciones VALUES(40102,'ACCENDO BANCO');
INSERT INTO clave_instituciones VALUES(40103,'AMERICAN EXPRES');
INSERT INTO clave_instituciones VALUES(40106,'BANK OF AMERICA');
INSERT INTO clave_instituciones VALUES(40108,'MUFG');
INSERT INTO clave_instituciones VALUES(40110,'JP MORGAN');
INSERT INTO clave_instituciones VALUES(40112,'BMONEX');
INSERT INTO clave_instituciones VALUES(40113,'VE POR MAS');
INSERT INTO clave_instituciones VALUES(40124,'DEUTSCHE');
INSERT INTO clave_instituciones VALUES(40126,'CREDIT SUISSE');
INSERT INTO clave_instituciones VALUES(40127,'AZTECA');
INSERT INTO clave_instituciones VALUES(40128,'AUTOFIN');
INSERT INTO clave_instituciones VALUES(40129,'BARCLAYS');
INSERT INTO clave_instituciones VALUES(40130,'COMPARTAMOS');
INSERT INTO clave_instituciones VALUES(40132,'MULTIVA BANCO');
INSERT INTO clave_instituciones VALUES(40133,'ACTINVER');
INSERT INTO clave_instituciones VALUES(40136,'INTERCAM BANCO');
INSERT INTO clave_instituciones VALUES(40137,'BANCOPPEL');
INSERT INTO clave_instituciones VALUES(40138,'ABC CAPITAL');
INSERT INTO clave_instituciones VALUES(40140,'CONSUBANCO');
INSERT INTO clave_instituciones VALUES(40141,'VOLKSWAGEN');
INSERT INTO clave_instituciones VALUES(40143,'CIBANCO');
INSERT INTO clave_instituciones VALUES(40145,'BBASE');
INSERT INTO clave_instituciones VALUES(40147,'BANKAOOL');
INSERT INTO clave_instituciones VALUES(40148,'PAGATODO');
INSERT INTO clave_instituciones VALUES(40150,'INMOBILIARIO');
INSERT INTO clave_instituciones VALUES(40151,'DONDE');
INSERT INTO clave_instituciones VALUES(40152,'BANCREA');
INSERT INTO clave_instituciones VALUES(40154,'BANCO FINTERRA');
INSERT INTO clave_instituciones VALUES(40155,'ICBC');
INSERT INTO clave_instituciones VALUES(40156,'SABADELL');
INSERT INTO clave_instituciones VALUES(40157,'SHINHAN');
INSERT INTO clave_instituciones VALUES(40158,'MIZUHO BANK');
INSERT INTO clave_instituciones VALUES(40160,'BANCO S3');
INSERT INTO clave_instituciones VALUES(90600,'MONEXCB');
INSERT INTO clave_instituciones VALUES(90601,'GBM');
INSERT INTO clave_instituciones VALUES(90602,'MASARI');
INSERT INTO clave_instituciones VALUES(90605,'VALUE');
INSERT INTO clave_instituciones VALUES(90606,'ESTRUCTURADORES');
INSERT INTO clave_instituciones VALUES(90608,'VECTOR');
INSERT INTO clave_instituciones VALUES(90613,'MULTIVA CBOLSA');
INSERT INTO clave_instituciones VALUES(90616,'FINAMEX');
INSERT INTO clave_instituciones VALUES(90617,'VALMEX');
INSERT INTO clave_instituciones VALUES(90620,'PROFUTURO');
INSERT INTO clave_instituciones VALUES(90630,'CB INTERCAM');
INSERT INTO clave_instituciones VALUES(90631,'CI BOLSA');
INSERT INTO clave_instituciones VALUES(90634,'FINCOMUN');
INSERT INTO clave_instituciones VALUES(90636,'HDI SEGUROS');
INSERT INTO clave_instituciones VALUES(90638,'AKALA');
INSERT INTO clave_instituciones VALUES(90642,'REFORMA');
INSERT INTO clave_instituciones VALUES(90646,'STP');
INSERT INTO clave_instituciones VALUES(90648,'EVERCORE');
INSERT INTO clave_instituciones VALUES(90652,'CREDICAPITAL');
INSERT INTO clave_instituciones VALUES(90653,'KUSPIT');
INSERT INTO clave_instituciones VALUES(90656,'UNAGRA');
INSERT INTO clave_instituciones VALUES(90659,'ASP INTEGRA OPC');
INSERT INTO clave_instituciones VALUES(90670,'LIBERTAD');
INSERT INTO clave_instituciones VALUES(90677,'CAJA POP MEXICA');
INSERT INTO clave_instituciones VALUES(90680,'CRISTOBAL COLON');
INSERT INTO clave_instituciones VALUES(90683,'CAJA TELEFONIST');
INSERT INTO clave_instituciones VALUES(90684,'TRANSFER');
INSERT INTO clave_instituciones VALUES(90685,'FONDO (FIRA)');
INSERT INTO clave_instituciones VALUES(90686,'INVERCAP');
INSERT INTO clave_instituciones VALUES(90689,'FOMPED');
INSERT INTO clave_instituciones VALUES(90902,'INDEVAL');
INSERT INTO clave_instituciones VALUES(90903,'CoDi Valida');
INSERT INTO clave_instituciones VALUES(90814,'SANTANDER2');
INSERT INTO clave_instituciones VALUES(846,'GEM-STP');
